version: '2.1'

services:

  base-etl:
    build:
      context: .
    environment:
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      DISABLE_SCHEDULER: ${DISABLE_SCHEDULER}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}

  etl:
    extends:
      service: base-etl
    volumes:
    volumes:
      - .:/code
      - pomi-etl-output:/code/output
      - pomi-etl-node-modules:/code/node_modules

volumes:
  pomi-etl-node-modules:
  pomi-etl-output:
