version: '2.1'

services:

  base-etl:
    build:
      context: .
    volumes:
      - .:/code
      - pomi-etl-output:/code/output
    environment:
      ETL_SCHEDULE: ${ETL_SCHEDULE}

  etl:
    extends:
      service: base-etl
    volumes:
      - pomi-etl-node-modules:/code/node_modules
    ports:
      - 80:80

volumes:
  pomi-etl-node-modules:
  pomi-etl-output:
