version: '2.1'

services:

  test-etl:
    extends:
      file: docker-compose.yml
      service: base-etl
    command: yarn test
    volumes:
      - pomi-etl-node-modules-test:/code/node_modules
    environment:
      NODE_ENV: test

  test-ci:
    extends:
      file: docker-compose.yml
      service: base-etl
    command: yarn run test-ci
    volumes:
      - pomi-etl-node-modules-test:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  pomi-etl-node-modules-test:
