version: '2.1'

services:

  test-etl:
    extends:
      file: docker-compose.yml
      service: base-etl
    command: yarn test
    volumes:
      - pomi-etl-node-modules:/code/node_modules
    environment:
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}

  travis-tests:
    extends:
      file: docker-compose.yml
      service: base-etl
    command: yarn run travis
    volumes:
      - pomi-etl-node-modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: test
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

  travis-tests-integration:
    extends:
      file: docker-compose.yml
      service: base-etl
    command: yarn run test-integration
    volumes:
      - pomi-etl-node-modules:/code/node_modules
    environment:
      COVERALLS_REPO_TOKEN: ${COVERALLS_REPO_TOKEN}
      NODE_ENV: development
      SNYK_TOKEN: ${SNYK_TOKEN}
      TRAVIS: ${TRAVIS}
      TRAVIS_BRANCH: ${TRAVIS_BRANCH}
      TRAVIS_COMMIT: ${TRAVIS_COMMIT}
      TRAVIS_JOB_ID: ${TRAVIS_JOB_ID}

volumes:
  pomi-etl-node-modules:
  pomi-etl-output:
