version: '2'

services:

  etl:
    image: nhsuk/pomi-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      ETL_SCHEDULE: ${ETL_SCHEDULE}
    labels:
      traefik.enable: true
      traefik.frontend.rule: $TRAEFIK_RULE
      traefik.port: 80
      map-public-http: 80
