version: '2'

services:

  etl:
    image: nhsuk/pomi-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      ETL_SCHEDULE: ${ETL_SCHEDULE}
    labels:
      traefik.enable: stack
      traefik.domain: ${TRAEFIK_DOMAIN}
      traefik.port: 80
      map-public-http: 80
    volumes:
      - pomi-etl-output:/code/site/json
    logging:
      driver: splunk
      options:
        splunk-url: ${SPLUNK_HEC_URL}
        splunk-token: ${SPLUNK_HEC_TOKEN}
        splunk-insecureskipverify: "true"
        splunk-sourcetype: docker
        splunk-source: pomi-data-etl
        splunk-verify-connection: "false"

volumes:
  pomi-etl-output:
