version: '2'

services:

  etl:
    image: nhsuk/pomi-data-etl:${DOCKER_IMAGE_TAG}
    environment:
      ETL_SCHEDULE: ${ETL_SCHEDULE}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
    labels:
      io.rancher.container.pull_image: always
